version: '3'
services:
  python-scikit-image:
    image: yuichkun/python-scikit-image
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: wordpress
