version: '3'
services:
  python-scikit-image:
    image: yuichkun/starling-server
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: starling-server
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: starling-server
